image: go1com/ci-php:php7

mirror:
  tags: ["aws"]
  only: ["master"]
  script:
    - mkdir ~/.ssh
    - echo "$GITHUB_DEPLOY_PRIVATE_KEY"           > ~/.ssh/rest.deploy.pem
    - chmod 400 ~/.ssh/rest.deploy.pem
    - ssh-keyscan -H github.com                  >> ~/.ssh/known_hosts
    - echo ''                                    >> ~/.ssh/config
    - echo 'Host github.com'                     >> ~/.ssh/config
    - echo 'IdentityFile ~/.ssh/rest.deploy.pem' >> ~/.ssh/config
    - git push --force git@github.com:go1com/rest.git HEAD:refs/heads/master
    - git push git@github.com:go1com/rest.git --tags
